services:
  - type: web
    name: gestionstocke
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn redpos.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: gestionstocke-db
          property: connectionString
      - key: CSRF_TRUSTED_ORIGINS
        sync: false

databases:
  - name: gestionstocke-db
    databaseName: gestionstocke
    user: gestionstocke
